# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='username',
            field=models.CharField(default='abc', max_length=10, verbose_name='所属人'),
        ),
    ]
